---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-plus
  namespace: policies
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: policies
  source:
    path: policygenerator/policy-sets/stable/openshift-plus
    repoURL: https://github.com/ch-stark/policy-collection
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true           
