---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  name: policies
  namespace: policies
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: policies
  source:
    path: policygenerator/policy-sets/community/ocp-best-practices
    repoURL: https://github.com/ch-stark/policy-collection
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true           
