apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: gatekeeper-placement
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: gatekeeper, operator: In, values: ["true"]}
